### ISSUE TITLE
should we remove reflectance <= 0 points in data preprocess?

### ISSUE THREAD

**Issue by traveller59** [qianguih/voxelnet#5]
![test](https://user-images.githubusercontent.com/28866047/37865098-7f8546d4-2fb2-11e8-957d-e87be7bb6ff5.png)
Left keeps reflectance <= 0 points and right drop them, yellow is positive voxels and purple is negative. we can find that some important points are dropped.

**Comment by qianguih** [comment]
Nice observation. I am investigating how this impacts the performances. Will update in next commit if necessary.

**Comment by traveller59** [comment]
actually I can get 83/75/74 3d AP in my own implemention with your hyper parameters when keep reflectance==0 points, but my implemention has bad performance when drop reflectance==0 points.

**Comment by traveller59** [comment]
I have solved the bug(not limit angles to pi/2) and train 20 epochs with reflectance==0 points, and get result:
bv: 88.273483 86.023048 78.579391
3d: 87.182213 83.288345 76.851006
3d performance can greatly benefit from reflectance==0 points.

**Comment by brb-chen** [comment]
in the VFE layer, the reflectance is only part of the feature representation, XYZ coordination may contribute more in the entire architecture, checking the Loss Function, you may get the same conclusion. 

reflection and other original feature, such as normal vector can promote the performance, but not necessary, same thing in other direct point cloud consuming architecture, e.g pointnet(++)...

**Comment by traveller59** [comment]
@brb-chen this implemention currently remove all reflectance==0 points(not drop reflectance in feature encoding) in data preprocess so lots of positive voxels of hard examples are dropped, and leads to bad performance in moderate/hard eval.
I have tested the network that use a single linear+norm layer instead of all VFE and get almost same performance(only train 5 epochs). you are right, XYZ coordination is the most important feature of all features.

**Comment by qianguih** [comment]
@traveller59 keeping points with negative reflectance does also improve the performances in my case.  It will be updated in next commit.

**Comment by traveller59** [comment]
@qianguih there is a problem in your eval code, you should change overlap threshold {0.5, 0.25, 0.25} to official {0.7, 0.5, 0.5}

**Comment by traveller59** [comment]
@haotians not now. due to a bug in eval code, the performance of my implemention is greatly decreased after fix that bug(3d 87,83,76->60,50,50), and greatly worse than official performance. I need to tune the model.

**Comment by hriapatil** [comment]
@qianguih @traveller59 I noticed that the output labels are saved in "lidar" coordinates whereas for KITTI evaluation, they should be in "camera" coordinates [at this [link](https://github.com/qianguih/voxelnet/blob/4ede13972d5fc51bd8e8f9cc5ed4e8311842ee44/test.py#L79)]. Could this be the cause for performance drop?

**Comment by qianguih** [comment]
@traveller59 Thanks for sharing your code. It looks quite interesting. My implementation was able to achieve similar performances in bird view detection but failed to produce nice 3d detection results. I am still looking for bugs. if you have any, please feel free to share or create a pull request. : )

**Comment by traveller59** [comment]
@qianguih I can get 70/59/58 3d mAP(30 epochs) with some changes(still under tuning):
1. remove all empty anchors(contain no voxel, using summed-area algorithm), then every example has 5k-20k anchors
2. balanced sample 512 anchors in every example(this may be the most important change)
3. classification loss normed by num of positives + negatives, localization loss normed by num of positives
4. positive class weight and negative class weight all equal to one, localization loss weight is 2
5. score threshold=0.5
6. use another iou calculation method(get nearest 'standing' or 'lying' bbox then calculate iou)

**Comment by johleh** [comment]
@traveller59 

impressive result with 30 epochs, do you plan on sharing your code in the future ?
the changes sound interesting but i think i don't understand all of them from just a few sentences.

1. example = gt_object or frame? what is an empty voxel in the feature plane ? in my approach i filter all anchors that do not point into a (scaled) ground truth box, is it similar ?
2. you randomly look at and evaluate 512 anchors per gt_object/frame or do you use something like a grid around a gt_center and limit the the anchors to evaluate by distance?
3. here examples must be gt_objects right ?


@6. i think one could also compensate for the direction of the center offset relative to the object direction. an offset along the length axis of the object is better than an offset along the width axis of an object. it should be a bit more accurate this way for gt_objects with near diagonal orientations.

blue = ground truth, red anchor prediction without rotation
1. image: ground truth (40° yaw) and anchor with perfect size estimation
2. image: without compensation rotating ground truth to nearest orthogonal position.
3. image: additionally rotate the anchor offset around the gt_center with -yaw gt. (all in range -45 to 45 °)
![selection_026](https://user-images.githubusercontent.com/16760555/38778113-1cc686d0-40b4-11e8-8f0b-305ca0a1fc2e.png)

**Comment by traveller59** [comment]
@johleh I remove all data augmentation but random flip to make network converge faster, so I can get good result in 30 epoch.
1. 'example' means one data/image/pointcloud, do you have a better name because 'example' also means positive + negative in detection?
2. sample 512 anchors in training, keep all in inference.
3. number of examples means number of positives + negatives
4. 6 is converted from avod.  the most accurate way to calculate IoU is using rotate iou ([official implementation](https://github.com/hongzhenwang/RRPN-revise/tree/master/lib/rotation), my [numba.cuda version](https://github.com/traveller59/kitti-object-eval-python/blob/master/rotate_iou.py)). but this will lead to too little positives. The avod approach looks better than the 'standup' in this implementation.

* code share:
my implementation contains too much code relate to my own research, so I prepare to release code after reproduce official result successfully because arrange my code also takes time.

**Comment by traveller59** [comment]
@johleh sorry I can't understand the compensate method, where do you do compensate, in anchor generation/preprocess or in postprocess?

**Comment by traveller59** [comment]
@johleh I filter empty anchors by following step:
1. get voxels, coors from a point cloud
2. convert coors to a dense tensor
3. sum the dense tensor in height axis
4. get integral image of the dense tensor by cumsum
5. convert anchors to integral image coordinate system
6. use summed-area algorithm to determine whether the area of a anchor is zero.
code:
```Python
def image_box_region_area(img_cumsum, bbox):
    """check a 2d voxel is contained by a box. used to filter empty
    anchors.
    Summed-area table algorithm:
    ==> W
    ------------------
    |      |         |
    |------A---------B
    |      |         |
    |      |         |
    |----- C---------D
    Iabcd = ID-IB-IC+IA
    Args:
        img_cumsum: [M, H, W](yx) cumsumed image.
        bbox: [N, 4](xyxy) bounding box, 
    """
    N = bbox.shape[0]
    M = img_cumsum.shape[0]
    ret = np.zeros([N, M], dtype=img_cumsum.dtype)
    ID = img_cumsum[:, bbox[:, 3], bbox[:, 2]]
    IA = img_cumsum[:, bbox[:, 1], bbox[:, 0]]
    IB = img_cumsum[:, bbox[:, 3], bbox[:, 0]]
    IC = img_cumsum[:, bbox[:, 1], bbox[:, 2]]
    ret = ID - IB - IC + IA
    return ret

coors = coordinates
dense_voxel_map = np.zeros(grid_size[::-1])
dense_voxel_map[coors[:, 0], coors[:, 1], coors[:, 2]] = 1.0
dense_voxel_map = dense_voxel_map.sum(0)
dense_voxel_map = dense_voxel_map.cumsum(0)
dense_voxel_map = dense_voxel_map.cumsum(1)
vsize_bv = np.tile(voxel_size[:2], 2)
anchors_bv[..., [1, 3]] -= coors_range[1]
anchors_bv_coors = np.floor(anchors_bv / vsize_bv).astype(np.int64)
anchors_bv_coors[..., [0, 2]] = np.clip(
anchors_bv_coors[..., [0, 2]], a_max=grid_size[0] - 1, a_min=0)
anchors_bv_coors[..., [1, 3]] = np.clip(
anchors_bv_coors[..., [1, 3]], a_max=grid_size[1] - 1, a_min=0)
anchors_bv_coors = anchors_bv_coors.reshape([-1, 4])
anchors_mask = box_np_ops.image_box_region_area(
	dense_voxel_map[np.newaxis, ...], anchors_bv_coors).reshape(-1) > 0
```
I don't know what does 'point into a (scaled) ground truth box' mean.

**Comment by johleh** [comment]
@traveller59 
thank you for the quick reply, i still have some questions, i work on a pytorch implementation and it doesn't work nearly as well yet, so each answer you can share is very helpful to me.

1. pointcloud/frame/image are all good :). the removal of empty anchors seems very important and makes a lot of sense with the cropped pointclouds, edit : thanks for the explanation/code! 
2. balanced sampling like  [avod mini batch sampling](https://github.com/kujason/avod/blob/master/avod/core/minibatch_samplers/balanced_positive_negative_sampler.py) ? 1:1 neg:pos?
3. interpretation a.  unlike in the paper you divide both pos/neg loss by the sum of pos and neg examples, right ?  images with many labels will have higher positive error than those with only a few, which makes sense to me because they contain more information about positive objects too.
interpretation b. just like the paper states and i misunderstood.
4. iou calculation + compensation: 
i recognized the avod method and i use it myself too. my approach is more centered on ground truth objects, for each ground truth object i only evaluate anchors that point into a ground truth box. (if their predicted center is not within the ground truth box, the anchor can't reach good iou anyways. eg. gt_box * 1.2 for 45% iou threshold) and then modify their centers relative to the angle that is used to rotate the ground truth in an orthogonal orientation.
the overall number of positives should not change, it just accepts a few more where the offset is mainly along the longer axis (and therefore lower relative offset) and  rejects a few more where the offset is mainly along the shorter axis of an object with near diagonal angle.
in this implementation it would mean to take a label, modify all anchors, perform iou between anchors and only this label and repeat for all labels. But it should be only a small improvement for near diagonal labels and shouldn't have any effect if use no rotation-augmentation, because most labels are near the orthogonal axis in the kitti dataset.
 - compensation step (or correction maybe better):
    correction angle = angle between ground truth and 0°/90° axis // difference to get orthogonal ground truth
    modified anchor_pred_ center_xy = rotate by negative correction angle( anchor_pred_center_xy - gt_center_xy ) + center_gt_xy   // works for correction angles between -45° and 45°
5. when using the avod iou-method i have a large disparity between the 2 anchor types. in the kitti set there are only about 1/6th  ground truth labels that are lying down and these anchor boxes only see few positive examples for regression, learn slower and perform much worse for me. how did you solve that imbalance ?

**Comment by traveller59** [comment]
@johleh actually my implementation contains both pytorch and tensorflow version that share same config and much code. all results in this issue are produced by pytorch code.
After a night of training, I get following performance(best result, with all data aug, 136k step, batch_size=3):
```
Car mAP@0.70, 0.70, 0.70:
bbox mAP:89.38, 82.90, 78.01
bev  mAP:89.09, 83.14, 78.20
3d   mAP:79.90, 64.82, 61.08
Car mAP@0.70, 0.50, 0.50:
bbox mAP:89.38, 82.90, 78.01
bev  mAP:96.83, 88.91, 88.03
3d   mAP:90.15, 88.14, 86.66
```
aug steps:
```Python
        gt_boxes, points = prep.random_flip(gt_boxes, points)
        gt_boxes, points = prep.apply_noise_per_groundtruth(gt_boxes, points)
        gt_boxes, points = prep.global_rotation(gt_boxes, points)
        gt_boxes, points = prep.global_scaling(gt_boxes, points)
        gt_boxes = prep.filter_gt_box_outside_range(gt_boxes, bv_range)
        # limit rad to [-pi, pi]
        gt_boxes[:, 6] = box_np_ops.limit_period(gt_boxes[:, 6], offset=0.5, period=2*np.pi)
```
if without data aug, network will overfit after 30 epochs.
1. remove empty anchors doesn't have benefit if without sample in my case.
2. yes, but number of positives is not enough to do 1:1 sampling. 
3. the norm method only affect pos/neg weights, 2d detectors in tensorflow use this norm approach. norm by number of pos/neg may change the score threshold but I guess it don't matter.
4. The most important thing is you can't do compensation when inference, your compensation seems want to make anchors has more iou with groundtruth, but when inference, which anchors should the box predictions be linked to?
5. I don't deal with this imbalance. the problem should come from other places.

**Comment by johleh** [comment]
thanks a lot for all these tips. it is good to know that the model works and that i just have to find the errors in my implementation

- @4. yes it is just for training, and maybe it is not beneficial anyways (it should be good for detection, but maybe it is detrimental for regression). in inference i simply generate all anchor boxes and perform non maximum suppression.

- @5. the imbalance is in the dataset there are mostly ground truth labels with the same orientation as the kitti car, maybe i do something wrong. do you regress both anchor types for each ground truth ? because one of the anchor boxes has very low iou when comparing to lying standing ground truth and i only choose the best anchor type and ignore the other one.

would it be possible to use 2 types of positive examples, one iou threshold to learn detection (could be higher, and even the exact 3D iou) and one iou threshold to choose the samples from which the model learns the bounding box regression (could be lower to start out with more examples) ?

**Comment by traveller59** [comment]
@johleh 
4. I'm not sure the compensation is beneficial for classification because this may force network learn a strange pattern, the approach in avod seems can make network pay more attention to centers in classification but I haven't observed significant error change in angles and centers. you can plot a pos/neg map to determine whether this approach can generate appropriate map. 
5. each point in feature map will regress two offsets (0, pi/2). There is a imbalance for lying anchors in classification but this seems don't impact on network performance. I will try to assign weights for them later. In addition, I have tried to remove one anchor per localization by score in postprocess several weeks ago but had no benefit. so just regardless of this imbalance for now.

use different iou threshold between classification and regression should work but will force backbone network learn more features which may isn't beneficial to classification. you can add a sub-network for regression after reproduce official performance.

**Comment by johleh** [comment]
@traveller59 
- i think i understand the deleting empty voxels step. it is a sanity check that deletes all anchor proposals, where the proposed 2D box doesn't contain a single lidar point (summed up over height) . and is useful for both training and inference. in a trained model these deleted proposals shouldn't pass the detection threshold i guess or would be an indicator for heavy overfitting right ?

- i overstated the imbalance, after looking again it is only about 3:1. standing : lying
nevertheless how do you regress both anchor box types for one ground truth, would not a lying anchor_type have very low iou for a standing ground truth ? this is something i don't understand yet.
As i understand it one takes the axis aligned anchor box proposals and compares them to the axis aligned ground truth box. This results in one type with perfect alignment and the other will be perpendicular. i only regress the aligned type because the other one is far below the threshold.

**Comment by traveller59** [comment]
@johleh 
1. empty anchors should be completely removed. they indicate very easy examples that will dilute grads produced by important examples. if don't remove them when do balanced sampling, your sampled minibatch will contain too much empty and useless examples. In addition, if you train with all data aug, overfitting is not significant.
2. iou between 'lying' or 'standing' is low, but you can't label a localization with 'lying' or 'standing' in inference, when training, network need to use negatives produced by 'wrong posture' anchors to do classification when inference.

**Comment by johleh** [comment]
@traveller59 
1. sorry i didn't want to suggest that you do it because of overfitting and i understand it greatly improves the quality of negative samples during training. i just tried to imagine how a trained model in inference mode would produce empty anchor proposals with higher confidence than the threshold, and overfitting was the first that came to my mind. 
2. yes i also use the results of both anchor types for the detection map, but for the regression/localisation/box error only one of the anchor types has a chance to generate positive samples. if one uses positive samples only for box regression, the lying anchor is trained with much less data in my case. 
3. when looking at the heatmaps i often observe the situation where 2 objects are close and object 1 is recognized well and object 2 is not. most of the anchors in that area learn to focus (predict centers) on the well recognized object 1, which leaves fewer anchors for the other one. with frame-wide balanced sampling one will get lots of positives for object 1 and only a few for object 2 (fewer anchors that focus, and those that do do not perform that well yet), but the model has to learn a lot more about object 2 to improve performance. i thought about additional balancing in a way that from every object a minimum share of positives is sampled.
4. i might have a bug in my feature encoding, can you overfit the model on training data without augmentation ? i can't even do that.

**Comment by traveller59** [comment]
@johleh 
What's your current performance in val kittiset?
I have upload my result. but get worse performance than official, especially 3d:
eval:
```
Car mAP@0.70, 0.70, 0.70:
bbox mAP:90.46, 86.20, 79.58
bev  mAP:89.87, 85.77, 79.25
3d   mAP:82.75, 67.29, 64.46
```
test:
```
Car (Detection) | 89.50 % | 79.55 % | 77.81 %
Car (3D Detection) | 69.04 % | 59.75 % | 52.93 %
Car (Bird's Eye View) | 84.57 % | 78.02 % | 75.77 %
```
official test:
```
Car (Detection) | 90.30 % | 85.95 % | 79.21 %
Car (3D Detection) | 77.47 % | 65.11 % | 57.73 %
Car (Bird's Eye View) | 89.35 % | 79.26 % | 77.39 %
```
There are still some problems in my implementation.
2. you want 'wrong posture' anchors also do regression backward in training?  This may beneficial for faster regression converge but your performance problem should from other place.
3. I don't have heatmap functions but I have a qt-based viewer to view anchors, 3d results, etc, and I haven't observed that phenomenon. The balanced sampling will keep almost all positives because of too little positives, so I can't understand why your object 1 has more anchors than object 2. I am using sampling method modified from FAIR [Detectron](https://github.com/facebookresearch/Detectron/blob/master/lib/roi_data/rpn.py)
4. I have deleted that training log which is overfitting, could you provide something about your eval performance?

**Comment by LinHungShi** [comment]
@traveller59  Did you preprocess the angle in other way? or you just disabled the angle limit function?

**Comment by traveller59** [comment]
@LinHungShi I only limit angles to -pi~pi in preprocessing, you can try angle vector encoding described in AVOD.

**Comment by LinHungShi** [comment]
@traveller59 thanks for your swift reply. According to readme file in development kit, it seems the angle is set within [-pi, pi] by default. Do you do anything else or just modify the function to limit it within [-pi, pi] ? Thanks~

**Comment by traveller59** [comment]
@LinHungShi data augmentation such as global rotation and noise per object may cause angles out of range, so need to limit them after augmentation if directly predict radian offset.

**Comment by ansabsheikh9** [comment]
@traveller59 do you remove occluded or truncated cars while training?

**Comment by traveller59** [comment]
@ansabsheikh9 no, I only remove out-of-range objects.

**Comment by LinHungShi** [comment]
@traveller59  thanks for your advice, I will take care of that part. BTW, could you share the hyper-parameters such as alpha,beta learning rate and training epoch for your model with the best performance so far?

**Comment by traveller59** [comment]
@LinHungShi Adam optimizer with 0.0002 initial learning rate and exponential decay, 160 epoch. I don't use the loss described in original paper and use loss in 2d image detectors instead. some parameters are described above.

**Comment by LinHungShi** [comment]
Many thanks for your reply. You mentioned that we could remove unknown examples and the corresponding point. I assume that you mean dontcare examples, am I correct? If it is, since the dimension and location of the boxes is not given (which is set -1000 by default) and only 2d boxes in the image coordinate is given, could you let me know how you project it back to lidar space?

**Comment by traveller59** [comment]
@LinHungShi unknown ground-truths means ground-truths not belong to Easy, Moderate and Hard difficulty in KITTI evaluation. you don't need to remove them, otherwise will slightly decrease performance(1-2 AP) in my case.
I ignore all DontCare in label file.

**Comment by LinHungShi** [comment]
@traveller59  Thanks. You mentioned out-of-range objects, do you mean those objects out-of-image after data augmentation? In addition, are you using rotation as the only data augmentation? Do you do any modification on the model structure? After some modification as indicated above, my performance still much worse than yours. For instance, after modifying angle_in_limit and limit the angle within [-pi, pi], the error of angle prediction starts increasing. I would appreciate if you could give me some hints~

**Comment by traveller59** [comment]
@LinHungShi out of point cloud range(0-70.4, -40-40, -3-1), all data augmentation. the [-pi, pi] should be used with angle vector encoding, I haven't tuned the raw angle encoding method yet. the nms score threshold need be determined by your training PR curve. Result above has no modification of model structure.

**Comment by LinHungShi** [comment]
@traveller59  you mentioned that you limit the angle within [-pi, pi]. How did you do that without modifying the method? As far as I know, this is the only place where the raw angle is preprocessed. Did you implement your own vfe layer?

**Comment by traveller59** [comment]
@LinHungShi sorry for late reply. modify which method?
```Python
def limit_period(val, offset=0.5, period=np.pi):
    return val - np.floor(val / period + offset) * period
```
VFE: no modification in above result.

**Comment by LinHungShi** [comment]
@traveller59  thanks for the reply. According to the method you provides, it seems you still limit the angle within [-pi/2, pi/2] ? For instance, when val is [0, pi/2, pi, -pi/2, -pi], offset is 0.5. The corresponding value after applying limit_period is [0, -pi/2, 0, -pi/2, 0]. Am I right?

**Comment by LinHungShi** [comment]
@traveller59  Hi, thanks for providing your method. My implementation has some problem and I can't get high recall even with low confidence after 200 epochs. Do you do any postprocessing? For instance, removing objects that are out-of-range.

**Comment by traveller59** [comment]
@LinHungShi Postprocessing in my code include remove low score, nms with rotate IoU, remove out of range 2d bboxes and remove out of range objects based on center(only useful for people detection).
The classification recall(training) in my case can achieve 0.96(average of total training) in 0.1 threshold, I haven't calculated other recall. Note that this may depend on your method of generating classification targets.

**Comment by LinHungShi** [comment]
@traveller59  After looking into validation error, I find that pos class error and reg loss increases after 20 epochs. In addition, my recall is very low, which below 0.9 with threshold 1. In addition, lots of objects with standing box (90 degree rotated from anchors) are not detected. I have applied more augmentation techniques, such as flip and noise you mentioned before, and increase alpha to 2, but still happens... Have you ever suffered such problem? I am wondering if it's the problem of batch size.

**Comment by traveller59** [comment]
@LinHungShi Batch size shouldn’t be the problem. I am using same weight for pos and neg classification loss, so you don’t need to modify alpha and beta from this implementation. 
Do you eval performance in 0.5 or lower threshold? There should be some problem with your target generation if too much stand objects aren’t detected with 0.5 eval threshold comparing with lying objects. Do you remove empty anchors during training and inference?
loss Increase: overfitting. Check your data augmentation by visualization and try to increase some noise parameter. I am using overall average metric to record loss and PR and haven’t notice this kind of problem.

**Comment by ansabsheikh9** [comment]
@traveller59 thank you for sharing your code of limit_period
I am using your function. I have one question. I am using these values.
ry = 1.62 (which is 92.81 degrees)
rz = -ry - np.pi /2
rz = limit_prediod(rz)
then I get rz as  -0.0492 which is aprox -2.81 degree
but i should get 3.09 which is +177.2 degrees.
Why do we limit the angle from -pi/2 to pi/2
as target angles are from -pi to pi

**Comment by traveller59** [comment]
@ansabsheikh9 That is just a default argument, I use period=2*np.pi to limit angle to [-pi, pi]. This function move all values of a periodic function to the period near zero.

**Comment by ansabsheikh9** [comment]
@traveller59 thank you for your prompt reply. 
Is there any reasoning of limiting the angle to limit angle to -pi/2 to pi/2 like in this implementation.
https://github.com/qianguih/voxelnet/blob/b74823daa328fc2fa99452bf79793e1f3c32c72a/utils/utils.py#L58 or I am missing something.

**Comment by traveller59** [comment]
@ansabsheikh9 box with angle and angle + pi have same bird's eye view box. so drop direction information may make angle prediction easier and increase AP performance.

**Comment by ansabsheikh9** [comment]
@traveller59 You mentioned that you are doing different augmentations on each sample.
while in this implementation they are doing one type randomly each time.
I tried three types at the same but my accuracy reduced. 
Could you please comment on your data augmentation technique in more detail. 
Thank you

**Comment by traveller59** [comment]
@ansabsheikh9 training with all augmentation need long time to converge(100+ epochs). my data augmentation is same as the voxelnet paper except adding random flip. The code look like this:
```Python
prep.noise_per_object_(gt_boxes_lidar, points)
gt_boxes_lidar, points = prep.random_flip(gt_boxes_lidar, points)
gt_boxes_lidar, points = prep.global_rotation(gt_boxes_lidar, points)
gt_boxes_lidar, points = prep.global_scaling(gt_boxes_lidar, points)
```

**Comment by sedatester** [comment]
Hi, @qianguih, @traveller59! Thanks a lot for the implementation and tips on improving the performance, they have been really useful. I am looking to improve the inference time now, do you guys have any useful tips for that for this implementation according to your experience? Thanks!

**Comment by Manueljohnson063** [comment]
Hi guys could you please help how to addd multiple objects for training like car and pedestrian

**Comment by GuidanceMantras** [comment]
@Manueljohnson063  we need to change the code. Now the code is just implemented for binary classification, we need to use softmax instead of sigmoid. And also we need to make some changes in the code after p_map in rpn.py (line number 93).
